import continuum_models_systems_particles_arising_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace continuum_models_systems_particles_arising_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end continuum_models_systems_particles_arising_theorem_canonical_lane_mathlib
end HautevilleHouse
